name: Build rpv-web

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths:
      - frontend/**
      - src/**
      - Makefile
      - .github/workflows/build.yml

jobs:
  build-rpv-web-x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Install V
        uses: vlang/setup-v@v1.4

      - name: Install mingw
        run: |
          sudo apt install -y gcc-mingw-w64

      - name: Build rpv-web-x64
        run: |
          v install qtc-de.rpv
          make

      - name: Archive rpv-web-x64
        uses: actions/upload-artifact@v4
        with:
          name: rpv-web-x64
          path: rpv-web-x64.exe

  build-rpv-web-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Install V
        uses: vlang/setup-v@v1.4

      - name: Install mingw
        run: |
          sudo apt install -y gcc-mingw-w64

      - name: Build rpv-web-x86
        run: |
          v install qtc-de.rpv
          cp ~/.vmodules/qtc_de/rpv/alternate/default-x86.v ~/.vmodules/qtc_de/rpv/internals/rpc-internal-structs.v
          make rpv-web-x86

      - name: Archive rpv-web-x86
        uses: actions/upload-artifact@v4
        with:
          name: rpv-web-x86
          path: rpv-web-x86.exe

  build-frontend:
    runs-on: ubuntu-latest
    needs:
      - build-rpv-web-x86
      - build-rpv-web-x64

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
          mv dist ../dist

      - name: Download rpv-web-x64
        uses: actions/download-artifact@v4
        with:
          name: rpv-web-x64

      - name: Download rpv-web-x86
        uses: actions/download-artifact@v4
        with:
          name: rpv-web-x86

      - name: Archive frontend and rpv-web
        uses: actions/upload-artifact@v4
        with:
          name: rpv-web
          path: |
            dist
            rpv-web-x64.exe
            rpv-web-x86.exe
